/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class clip_c_macClipboardNative */

#ifndef _Included_clip_c_macClipboardNative
#define _Included_clip_c_macClipboardNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     clip_c_macClipboardNative
 * Method:    setClipboardFiles
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_clip_c_macClipboardNative_setClipboardFiles
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
